### ISSUE TITLE
Can't get CG Timer to read from our Server running 2.0.7

### ISSUE THREAD

**Issue by rossmase** [jcalado/cgtimer#4]
Hi There,

We can't get CasparCG to read from our server. We've configured the pre-defined OSC clients using the Frontend and the config file looks correct as per your instructions. The only thing we're wondering is if Controllers being on AMCP might be causing issues?

Config reads

```
<osc>
    <default-port>6251</default-port>
    <predefined-clients>
      <predefined-client>
        <address>192.168.11.12</address>
        <port>6251</port>
      </predefined-client>
    </predefined-clients>
  </osc>
  <controllers>
    <tcp>
      <port>5250</port>
      <protocol>AMCP</protocol>
    </tcp>
  </controllers>
</configuration>
<!--
```

Any ideas? Really keen to use this as it looks great! 👍

**Comment by jcalado** [comment]
Hi!

Have you tried changing your <default-port>6251</default-port> back to 6250?

**Comment by rossmase** [comment]
Hi,

We've tried that unfortunately! Just tried again and no luck. We're running the server on Windows and the client on Mac and all firewalls are off. Would it help if I sent through the full config?

Thanks,

Ross

**Comment by jcalado** [comment]
I've got to check 2.0.7, maybe something is off with the protocol.
I'll get back to you on this.

EDIT: Yes, the format of the OSC messages used in 2.0.7 is incompatible with the app right now.
I'll try to work around it and post here when fixed!

**Comment by jcalado** [comment]
Hey! 

Getting back to you on this, release 1.1.1 (https://github.com/jcalado/cgtimer/releases/tag/v1.1.1) should fix this!
Can you please test and report back?

**Comment by jcalado** [comment]
Closing this as fixed.

**Comment by rossmase** [comment]
Hey! Sorry for the delay here we got swept up with some other bits but reviewing this now.

I'm still having issues but I'm going to try a few more things to see if we can get any luck. Just to confirm this should work on any other computer on the same LAN as the Caspar CG server?

**Comment by jcalado** [comment]
Have you tried changing your predefined port to something other than the same port that you are using on <predefined-client>?

Please try this for OSC segment of configuration:

```
  <osc>
    <default-port>6250</default-port>
    <disable-send-to-amcp-clients>false</disable-send-to-amcp-clients>
    <predefined-clients>
      <predefined-client>
        <address>192.168.11.12</address>
        <port>6251</port>
      </predefined-client>
    </predefined-clients>
  </osc>
```

**Comment by rossmase** [comment]
Hey Joel,

Do you mean changing this in the Caspar CG config file on the server?

Does CG timer need to run on the same machine as the Caspar CG Server?
Currently we're running it on another machine and want to have a producers
laptop using the timer so they can see time remaining e.t.c but not sure if
we're getting the wrong end of the stick around CG Timers functionality!

Thanks,

Ross

**Comment by jcalado** [comment]
Yes, please change the server default OSC port.
CGtimer can run on any machine within the same network, that is exactly it was meant to do 👍

**Comment by rossmase** [comment]
Hi Joel,

We've tried both options but still not working. We also tried on 2.3.0 and
no luck. Config for 2.3.0 below:

<?xml version="1.0" encoding="utf-8"?>


<configuration>

    <paths>

        <media-path>media/</media-path>

        <log-path>log/</log-path>

        <data-path>data/</data-path>

        <template-path>template/</template-path>

    </paths>

    <lock-clear-phrase>secret</lock-clear-phrase>

    <channels>

        <channel>

            <video-mode>1080p3000</video-mode>

            <consumers>

                <screen />

                <system-audio />

                <ndi>

                    <name>casparcg</name>

                    <allow-fields>false [true|false]</allow-fields>

                </ndi>

            </consumers>

        </channel>

    </channels>

    <controllers>

        <tcp>

            <port>5250</port>

            <protocol>AMCP</protocol>

        </tcp>

    </controllers>

    <amcp>

        <media-server>

            <host>localhost</host>

            <port>8000</port>

        </media-server>

    </amcp>

</configuration>





Any ideas?


Thanks,


Ross

**Comment by jcalado** [comment]
You still haven't tried what I asked.
Please change this part:

```
<osc>

    <default-port>6251</default-port>
```

to 

```
<osc>

    <default-port>6250</default-port>
```

**Comment by rossmase** [comment]
Hi Joel,

Apologies, we did try that and then tried changing the default port to 6251 again to see if we had any luck but neither worked. Appreciate it's probably something our side so I'll give it another go with a fresh head on Monday.

Thanks for your help so far.

**Comment by jcalado** [comment]
Can you check if other OSC apps work with casparcg server?
Please Check firewall settings on casparcg server machine.

**Comment by rossmase** [comment]
Hi Joel,

We finally sat down and tried to get our heads around the config file, we
decided we needed to face our fears!

I can confirm, we now have this running on 2.3.0 and it's great. Thank you
for your help and sorry for being noobs!

**Comment by jcalado** [comment]
Ah, great news!
I'm happy for you! :)

**Comment by vfmradio** [comment]
Hello, it still doesn't work with 2.0.7. Is there any way to fix this? I would be grateful for any help.
